#!/usr/bin/bash

cd /var/www/johnsnook/yii2-parsel

APIDOC='/var/www/bas.snooky/vendor/bin/apidoc'
YII2='/var/www/bas.snooky/vendor/yiisoft/yii2'

$APIDOC api src docs

$APIDOC guide src docs

sed -i 's/Yii Framework 2.0 API Documentation/Yii2 Parsel API Documentation/g' docs/*html
sed -i 's/The Definitive Guide to Yii 2.0/The Definitive Guide to Yii2 Parsel/g' docs/*html
